services:


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    ports:
      - "7700:8000"
    depends_on:
      - db

    command:  >
      bash -c "
        alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000
      "


volumes:
  db_data:
    driver: local
